### ISSUE TITLE
Filter by workflow

### ISSUE THREAD

**Issue by seagullmouse** [cunla/ghactions-manager#98]
**Is your feature request related to a problem? Please describe.**
I work on a large monorepo that has a lot of different workflows. I can't easily see which workflow is running and/or filter

**Describe the solution you'd like**
Add a filter option for workflow. I.e. add another option to the filters Actor, Status, Branch, Event, Workflow

**Comment by cunla** [comment]
Hi,

I will work on this soon.

Flow:
- Get worflows: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28 - list names in filter
- Workflow run has `workflow_id` which corresponds to workflows.

**Comment by cunla** [comment]
Well, it turns out github api does not support filtering by workflow:
https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28

It is possible to workaround it by doing the filter on the plugin, but it will mean a significant overhead of extra API calls (basically, get all workflow runs and filter out based on the selected workflow on the plugin).
Open a request for github to include filtering by workflow_id and then it should be easy to achieve.

**Comment by cunla** [comment]
https://github.com/orgs/community/discussions/70753

**Comment by cunla** [comment]
https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-workflow
